### ISSUE TITLE
Update catch_human_agent.py with updated dm_env_adaptor.py behavior

### ISSUE THREAD

**Issue by AurelianTactics** [deepmind/dm_env_rpc#2]
An update to dm_env_adaptor.py (https://github.com/deepmind/dm_env_rpc/commit/7a06811544a8cb4ce3f460a2afa3bd4ed8e80a24#diff-2c755513ee4f5f32331e60c10ce8ef602679781e87629139b0ba03db85848ab0) changed the default behavior that this script relied upon. This script assumes the reward will be packed into the step_result.observation[_OBSERVATION_REWARD] as it was previously with dm_env_adaptor calls prior to the updated. 

I believe that the current behavior requires that if you want the reward to be included into the observation you have to send it as an argument to dm_env_adaptor.py for example:
``` 
env, world_name = dm_env_adaptor.create_and_join_world( ..., requested_observations=[_OBSERVATION_BOARD, _OBSERVATION_REWARD])
```
The other way to get the reward is to call it from step_result.reward itself.

See pull request for one possible fix.

**Comment by tomwardio** [comment]
Thanks for reporting this! I don't see your PR, but this has subsequently been fixed [this commit](https://github.com/deepmind/dm_env_rpc/commit/fdb05516dd95f75382998a704dce1a35487e3532). Hopefully this clarifies how the `dm_env_adaptor` should be used.
